# Generated by Django 3.2 on 2021-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('artist', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=260)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
