# Generated by Django 3.2 on 2021-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
