# Generated by Django 3.2 on 2021-05-02 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exhibit_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
