# Generated by Django 3.2 on 2021-05-02 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exhibit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='price',
            field=models.IntegerField(default=100.00),
            preserve_default=False,
        ),
    ]
