# Generated by Django 3.2 on 2021-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exhibit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='price',
            field=models.FloatField(),
        ),
    ]
